config/routes.rb
Rails.application.routes.draw do

   root 'books#index'
   resources :books

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :set_book, only: [:show, :edit, :update, :destroy]

  respond_to :html, :xml, :json

  def index
    @books = Book.all
    respond_with(@books)
  end

  def show
    respond_with(@book)
  end

  def new
    @book = Book.new
    respond_with(@book)
  end

  def edit
  end

  def create
    @book = Book.new(book_params)
    @data = Date.current() 
    @book.readDate = @data
    @book.save
    respond_with(@book)
  end


  def update
    @book.update(book_params)
    respond_with(@book)
  end


  def destroy
    @book.destroy
    respond_with(@book)
  end

   private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:author, :description, :rate, :readDate, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(@book,html: {:class => 'form-horizontal'}) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'Tytuł', :class => 'col-sm-2 control-label' %><br />
    <div class="col-sm-4"> <%= f.text_field :title, :class => 'form-control' %> </div>
  </div>



  <div class="form-group">
    <%= f.label 'Autor', :class => 'col-sm-2 control-label' %><br />
    <div class="col-sm-4"> <%= f.text_field :author, :class => 'form-control' %></div>
  </div>
  <div class="form-group">
    <%= f.label 'Ocena', :class => 'col-sm-2 control-label' %><br />
    <div class="col-sm-4"> <%= f.select :rate, ['1', '2','3','4','5'], :class => 'form-control' %></div>
  </div>
  <div class="form-group">
    <%= f.label 'Opis' , :class => 'col-sm-2 control-label' %><br />
    <div class="col-sm-4"> <%= f.text_area :description, :class => 'form-control' %></div>
  </div>
  <div class="actions">
  <div class="col-sm-2"></div>
    <%= f.submit 'Zapisz', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Przeczytane książki</h1>
<div class="container">
  <div class="row">
    <% @books.each do |book| %>
        <div class="col-sm-3 col-md-3">
          <div class="well">
            <h2 class="text-warning"><%= book.title %></h2>
            <p id="notice"><%= notice %></p>
            <p><span class="label label-success"><%= book.author %></span></p>
             <ul>
              <li><b>Przeczytana:</b> <%= book.readDate %></li>
              <li><b>Ocena:</b> <%= book.rate %></li>
            </ul> 
            <p><%= book.description %></p>
          </div>
        </div>
   <% end %>
  </div>
</div>

<br />

app/views/books/new.html.erb
<h1>Nowa książka</h1>

<%= render 'form' %>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3 col-md-3">
      <div class="well">
        <h2 class="text-muted"><%= @book.title %></h2>
        <p id="notice"><%= notice %></p>
        <p><span class="label label-default"><%= @book.author %></span></p>
        <ul>
          <li><b>Przeczytana:</b> <%= @book.readDate %></li>
          <li><b>Ocena:</b> <%= @book.rate %></li>
        </ul> 
      <p><%= @book.description %></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Books</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>


<body>

<div class="container">
      <div class="header">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation"><%= link_to 'Wszystkie', books_path %></li>
            <li role="presentation"><%= link_to 'Dodaj nową', new_book_path %></li>
          </ul>
        </nav>
        <h3 class="text-muted">Moje książki</h3>
      </div>


      <div class="row marketing">
        <%= yield %>
      </div>

      <footer class="footer">
        <p>&copy; Aga 2014</p>
      </footer>

    </div>
</body>
 </html>